apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-app
  template:
    metadata:
      labels:
        app: my-spring-app
    spec:
      containers:
      - name: my-spring-app
        image: 839953/my-spring-app
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-app
spec:
  type: LoadBalancer
  selector:
    app: my-spring-app
  ports:
  - port: 8080
    targetPort: 8080